### ISSUE TITLE
Crash on startup with version 1.0b49-MC1.7.10

### ISSUE THREAD

**Issue by nmarshall23** [meza/achievementbooks#1]
Just checking out your mod, was considering switching from HQM.  
However I am having an issue, I crash on startup.

http://pastebin.com/fSrSUCfN

**Comment by meza** [comment]
Thanks, let me check this

**Comment by meza** [comment]
@nmarshall23 would you mind testing with this? It should have it fixed.
If you confirm, I'll send it off to Curse

[achievementbooks-1.0-dev-MC1.7.10.jar.zip](https://github.com/meza/achievementbooks/files/776769/achievementbooks-1.0-dev-MC1.7.10.jar.zip)

**Comment by nmarshall23** [comment]
It's still bugged. Now It doesn't show up as a mod. NEI integration dump loaded mods does not list it.
Nor is it listed in the Mods main menu.

Oddly if I have both jars, the mod load and I can spawn a book.

**Comment by meza** [comment]
That is so weird. It's difficult as it works on my computer, which is no excuse. Will try to reproduce and fix it asap

**Comment by meza** [comment]
I found it. Should be on Curse very soon

**Comment by meza** [comment]
@nmarshall23 here you go! Does this work? https://minecraft.curseforge.com/projects/achievement-books/files/2382342/download

I tried it on a brand new install with this being the only mod.

**Comment by meza** [comment]
I'll assume it works, let me know if that's not the case
