### ISSUE TITLE
[1.11.2] The book has a broken purple texture

### ISSUE THREAD

**Issue by Lothrazar** [meza/achievementbooks#15]
Using achievementbooks-v1.0-MC1.11.2.jar

My book json: https://pastebin.com/znQAM2MZ

I didnt see anywhere in readme where to specify texture file or tell it to use default

![2017-04-09_00 51 38](https://cloud.githubusercontent.com/assets/621529/24835740/d05832e0-1cbe-11e7-9d0f-bd8115e43ecf.png)

**Comment by meza** [comment]
That is very weird. Can you post your `latest.log` please?

I'm assuming you've tried reloading the entire game, but just in case, could you try pressing F3 + T at the same time to reload textures?

**Comment by Lothrazar** [comment]
Yes here is the log. https://pastebin.com/Wu2hPGbS 

Tons of mods in here, i did a search and i didnt see anything about book_demo or book_modapck or achievement books.

**Comment by meza** [comment]
Hmm, that is very interesting. There aren't any indicators as to why it's not working. Also, it's not the default minecraft resource (the black and purple squares).

Is it possible for me to test the pack you're using?

**Comment by Lothrazar** [comment]
Just tried F3 T as well and didnt work.  Let me first try disabling optifine and disabling foam fix, if that doesnt fix it ill send u a curse modpack export

EDIT: removing these brings it back to the mojang black and purple: 
![2017-04-09_09 47 07](https://cloud.githubusercontent.com/assets/621529/24839114/94ee8b78-1d09-11e7-947d-d60e75a6fff0.png)

**Comment by Lothrazar** [comment]
Using the curse launcher you can import this .zip file as a modpack https://ufile.io/eabb7

Also mod list is here https://modlister.com/user/Lothrazar

PS thanks for responding so fast. working on a big 1.11.2 pack and i want lots of goals for the player

**Comment by meza** [comment]
Sounds like fun, I'm on it.
Didn't get the notification email of this, sorry for the late reply -.-'
