### ISSUE TITLE
Suggestion: Image and Command Support

### ISSUE THREAD

**Issue by DrDarkfire** [meza/achievementbooks#17]
First of all, as a modpack dev, this mod is incredible for me to use. The customization is brilliant.
My first suggestion is image support. In my pack I would like my achievement book to also work as a guide book. Images are a hallmark of good guide books.
My second suggestion is command support. What I mean by this is when a player completes a quest, a command could be run. For me, that would mean unlocking different crafting recipes.
These are the two things I want to see out of this mod. Everything else in it is absolutely stunning. Multiple guidebooks with custom IDs, recipes, and colors. Stunning.
Keep up the good work!

**Comment by meza** [comment]
Hey, thanks fot the suggestions! I'm planning an overhaul in about 2 weeks so they come at the right time. First, I want to release a 1.12 version for the current code and then add some tweaks + features.

Images are difficult, but I definitely want to add them. They are much needed.

The command block support is a tricky one, but let me have a good think about them. Initially I want to add a "damage value" indicator, so you could see and probe the completeness of a book.
For individual achievements, I'm not sure yet. There should be a solution though!

**Comment by meza** [comment]
Image support issue is #9 and the command block support is #18 :)
