### ISSUE TITLE
[1.11.2] Texture issue

### ISSUE THREAD

**Issue by isto2278** [meza/achievementbooks#19]
Hi =)

This might be a duplicate of #15 but it's not identical, so I thought I'd make a new issue. Feel free to close this if it's redundant.

My issue is, the achievement books also don't have any textures but they render as the default purple and pink square/block. I looked through my latest log and found nothing of interest concerning achievement books. Do you need a modlist?

Thanks in advance =)

EDIT: Just noticed the textures in the other isse also reverted to black and purple squares. Seems this here is obsolete =)

**Comment by meza** [comment]
Hey, can you paste your book config without the pages:[] part?

**Comment by isto2278** [comment]
Here it is: https://pastebin.com/VtQP65tL

I tried renaming/resetting the item and file to the default values (I think?) but that doesn't seem to solve the problem.

**Comment by TwitchtvCarbs** [comment]
Still nothing on a fix yet huh? Was going to try and make a custom texture pack including the books but would be great if it could be fixed on the back end ya know? XD
