### ISSUE TITLE
1.12.2

### ISSUE THREAD

**Issue by Sunekaer** [meza/achievementbooks#20]
Hey 

Any update on 1.12.2 version?

**Comment by meza** [comment]
I'm hellbent on doing it, just finding it very difficult to get the right amount of time necessary. I've actually scheduled 2 days for next week to attempt and make it a thing!

**Comment by Sunekaer** [comment]
Thanks for the update!

**Comment by Sunekaer** [comment]
Update?

**Comment by meza** [comment]
It's on the way. 99% completed :)

**Comment by AsheX1** [comment]
anything?

**Comment by meza** [comment]
There's a new beta release for 1.12.2
