### ISSUE TITLE
1.12 - No new books show up...

### ISSUE THREAD

**Issue by BlueYoshi68** [meza/achievementbooks#22]
Every time I make a new json file that's almost identical to the demo minus the book name change the list just shows the ID as 0 (for all of them besides the demo) and it never gives me any other book BESIDES the demo...what gives.

**Comment by furtabs** [comment]
Hmm sorry for the late response this is a known bug of the 1.12 version. I’ll try to fix it up for you soon

**Comment by BlueYoshi68** [comment]
just a bit late lol, cant even remember what this mod was
