### ISSUE TITLE
Book's item texture isn't showing up [1.0b82 - 1.10.2]

### ISSUE THREAD

**Issue by noamsm** [meza/achievementbooks#6]
I want to use this cool mod for my modpack and it works good. just a littel problem, ther is no textures for any of the book colors!

please fix,
Thx

**Comment by meza** [comment]
@bluefutureMC even after a complete reload?

**Comment by noamsm** [comment]
yeap

**Comment by meza** [comment]
I won't be able to fix this for the next 20 hours or so, but will do after. Hang tight, thanks for letting me know!

**Comment by noamsm** [comment]
Thanks for helping!

**Comment by noamsm** [comment]
Now the book works.... I don't know what happened.... thx

**Comment by meza** [comment]
Haha, great! I'll still try to reproduce the problem to see if there's anything I can done to prevent these glitches.

Let me know if it happens ever again
