### ISSUE TITLE
Problem with command usage

### ISSUE THREAD

**Issue by Lorexe** [meza/achievementbooks#8]
Hi,

I just making a modpack and I have a little problem with your mod.
When I use FTBUtilities "Server Info" page, your mod write his command usage in the chat 
http://i.imgur.com/BaeSJ3t.png

I can say you why it's do that : 
FTBU get all commands usage of all mods to make his _Commands Page_  ([source](https://github.com/LatvianModder/FTBUtilities/blob/master/src/main/java/com/feed_the_beast/ftbu/ServerInfoPage.java#L191))
You send a chat message for sub commands while you just need to return a string  ([source](https://github.com/meza/achievementbooks/blob/master/1.10.2/src/main/java/com/stateshifterlabs/achievementbooks/commands/MainCommand.java#L49))

An other small problem occured when you just write "/achievementbooks" : http://i.imgur.com/5fAtRgm.png
You should take a look at **CommandTreeBase** that help you to make sub commands class :) 

Have a nice day.

Versions : 
forge-12.18.3.2254 (1.10.2)
Achievement Books 1.0b82-MC1.10.2
FTBUtilities-1.10.2-3.4.3

**Comment by meza** [comment]
Hi Lorexe,

Great find, thanks for the info. I'm currently polishing everything up for a proper release, so this came at the perfect time!

**Comment by meza** [comment]
Hey, it should be fixed in the new updates that are already out!
